services:
  pg:
    image: postgres:17.2-alpine3.21
    env_file:
      - example.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_volume:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:11.5.1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:1.66.0
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" #web
      - "14268:14268"
      - "9411:9411"


volumes:
  postgres_users_volume:
  prometheus_data:
  grafana_data: